export default [
    { path: '', redirect: 'introduction' },
    { path: 'introduction', component: () => import('./introduction.md') },
    { path: 'installation', component: () => import('./installation.md') },
    { path: 'quickstart', component: () => import('./quickstart.md') },
    { path: 'structure', component: () => import('./structure.md') },
    { path: 'views', component: () => import('./views.md') },
    { path: 'library', component: () => import('./library.md') },
    { path: 'components', component: () => import('./components.md') },
    { path: 'css-modules', component: () => import('./css-modules.md') },
    { path: 'assets', component: () => import('./assets.md') },
    { path: 'test', component: () => import('./test.md') },
    { path: 'deployment', component: () => import('./deployment.md') },
    { path: 'commands', component: () => import('./commands.md') },
    { path: 'config', component: () => import('./config.md') },

    { path: 'editor', component: () => import('./editor.md') },
    { path: 'js-style', component: () => import('eslint-config-vusion/JavaScript.zh-CN.md') },
    { path: 'vue-style', component: () => import('./vue-style.md') },
];
